import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SideBar } from "./components/SideBar";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className='bg-[#030712] w-screen h-screen flex' style={{}}>
                    <SideBar />
                    <div className='p-2 flex-1 overflow-y-auto'>
                        <div className='flex-1 bg-gradient-to-b from-gray-950 via-gray-900 to-gray-950 min-h-screen lg:rounded-xl border border-transparent lg:border-gray-700 overflow-y-auto'>
                            <main className='max-w-4xl w-full mx-auto py-20 px-4 md:px-10 text-white'>
                                {children}
                            </main>
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
